---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"
    - debug: var=output.stdout_lines
    - name: Check that the somefile.conf exists
      stat:
       path: /etc/ansible/playbooks/local1.yaml
      register: stat_result

    - name: Create the file, if it doesnt exist already
      file:
       path: /etc/ansible/playbooks/local1.yaml
       state: touch
      when: not stat_result.stat.exists

    - name: Check that the somefile.conf exists
      stat:
       path: /home/siva/distros/apache-tomcat-8.5.56.tar.gz
      register: stat_result1

    - name: download file with custom HTTP headers
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.56/bin/apache-tomcat-8.5.56.tar.gz
        dest: /home/siva/distros
      when: not stat_result1.stat.exists
